server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        # 配置 Nacos 地址
        # server-addr: localhost:8848
        # 使用集群
        server-addr: 192.168.226.139:1111

management:
  endpoints:
    web:
      exposure:
        include: '*'
