server:
  port: 80

#这里只把feign做客户端用，不注册进eureka
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: false
    service-url:
      # 集群版本
      #defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
      # 单机版本
      defaultZone: http://eureka7001.com:7001/eureka/

#设置feign客户端超时时间（OpenFeign默认支持ribbon）
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的实际
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000


feign:
  hystrix:
    enabled: true